# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Release

on:
  release:
    types: [published]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: bof3ext.sln

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout bof3ext repo
      uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Checkout bof3ext_resources repo
      uses: actions/checkout@v4
      with:
        repository: TheRealBiggs/bof3ext_resources
        path: NewData

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Debug
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Debug ${{env.SOLUTION_FILE_PATH}}

    - name: Build Release
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=Release ${{env.SOLUTION_FILE_PATH}}

    - name: Create BOF3.CFG
      run: (echo 0 && echo a) > BOF3.CFG

    - name: Setup 7Zip
      uses: milliewalky/setup-7-zip@v2

    - name: Zip Debug artifacts
      run: 7z a -t7z -mx=9 -i!build/Debug/*.dll -i!build/Debug/*.txt -i!build/Debug/*.toml -i!build/Debug/*.cfg -i!BOF3.CFG -ir!NewData/ -x!NewData/.git/ -x!NewData/.gitignore debug.7z

    - name: Zip Release artifacts
      run: 7z a -t7z -mx=9 -i!build/Release/*.dll -i!build/Release/*.txt -i!build/Release/*.toml -i!build/Release/*.cfg -i!BOF3.CFG -ir!NewData/ -x!NewData/.git/ -x!NewData/.gitignore release.7z

    - name: Upload Debug artifacts to GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        file: debug.7z
        tag: ${{ github.ref }}

    - name: Upload Release artifacts to GitHub release
      uses: svenstaro/upload-release-action@v2
      with:
        file: release.7z
        tag: ${{ github.ref }}
